name: "Unit Tests"
on: [push, pull_request]

jobs:
  junit:
    name: "JUnit"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: "11"
      - run: ./mvnw test
